### ISSUE TITLE
背景画像のCSSの指定について

### ISSUE THREAD

**Issue by syuilo** [hage-gh/HageDesktop#2]
https://github.com/hage-gh/HageDesktop/blob/master/src/styles/main.css#L18

```
background: url('../images/wallpaper.jpg');
```

となっていますが、次のようにすると画面サイズに合わせて適切なサイズで表示される(画面を覆い隠せる最小のサイズに自動的にしてくれる)ので私的にはこちらの方が好みです。ご検討ください。

```
background: url('../images/wallpaper.jpg');
background-attachment: fixed;
background-position: center center;
background-size: cover;
```

``background-attachment: fixed`` ... 背景画像の位置を固定
``background-position: center center`` ... 中央に配置
``background-size: cover`` ... サイズを自動調整

**Comment by hage-gh** [comment]
thx
I use only `background-size: cover`.

**Comment by syuilo** [comment]
(これら3つ全てを指定しないと私が期待した表示にはなりません)
Thank you.
